Repository openedx/course-discovery, pull requests merged in 2021-01, with the labels that each got.

#2860 Fix jsi18n view error
  course_discovery/apps/core/tests/test_views.py
  course_discovery/urls.py
Labels: open-source-contribution, ready to merge

#2793 [SE-3515] Handle JSON decoder error is api returns 404
  course_discovery/apps/course_metadata/data_loaders/api.py
Labels: changes requested, open-source-contribution

#2889 [SE-3515] Handle JSON decoder error if api fails
  course_discovery/apps/course_metadata/data_loaders/api.py
Labels: needs triage, open-source-contribution

#2891 [SE-3515] Handle JSON decoder error if api fails
  course_discovery/apps/course_metadata/data_loaders/api.py
Labels: needs triage, open-source-contribution
